FROM ubuntu:20.04

RUN apt-get -y update && apt-get -y install python3 
RUN mkdir /home/app
EXPOSE 20001 20004

COPY . /home/app
WORKDIR /home/app
CMD python3 /home/app/server.py

# Dockerfile do servidor
